# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Date-Calc
version:      5.6
version_from: Calc.pm
installdirs:  site
requires:
    Bit::Vector:                   6.6
    Carp::Clan:                    5.3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
