--- #YAML:1.0
name:               Date-Calc
version:            6.2
abstract:           Gregorian calendar date calculations
author:
    - Steffen Beyer <STBEY@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Bit::Vector:  7.1
    Carp::Clan:   5.3
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    Carp::Clan:      6.01
    Date::Calc::XS:  6.2
